export default {
  primaryLight: 'Lato-Light',
  primaryRegular: 'Lato-Regular',
  primaryBold: 'Lato-Bold',
  primarySemiBold: 'Lato-SemiBold',

  title1: {
    fontFamily: 'Poppins',
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '700',
  },
  title2: {
    fontFamily: 'Poppins',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
  },
  subtitle1: {
    fontFamily: 'Poppins',
    lineHeight: 28,
    fontSize: 18,
  },
  subtitle2: {
    fontFamily: 'Poppins',
    lineHeight: 24,
    fontSize: 16,
  },
  headline1: {
    fontFamily: 'Poppins',
    fontSize: 96,
    lineHeight: 104,
    fontWeight: '800',
  },
  headline2: {
    fontFamily: 'Poppins',
    fontSize: 60,
    lineHeight: 68,
    fontWeight: '800',
  },
  headline3: {
    fontFamily: 'Poppins',
    fontSize: 48,
    lineHeight: 56,
    fontWeight: '800',
  },
  headline4: {
    fontFamily: 'Poppins',
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '800',
  },
  headline5: {
    fontFamily: 'Poppins',
    fontSize: 24,
    lineHeight: 36,
    fontWeight: '800',
  },
  headline6: {
    fontFamily: 'Poppins',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '800',
  },
  para_semibold: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700',
  },
  para_regular: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 24,
  },
  para_semibold_link: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  para_regular_link: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 24,
    textDecorationLine: 'underline',
  },
  para_strike: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 24,
    textDecorationLine: 'line-through',
  },
  btn_large_normal: {
    fontFamily: 'Poppins',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
  },
  btn_large_link: {
    fontFamily: 'Poppins',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  btn_medium_normal: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700',
  },
  btn_medium_link: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  btn_small_normal: {
    fontFamily: 'Poppins',
    fontSize: 12,
    lineHeight: 24,
    fontWeight: '700',
  },
  btn_small_link: {
    fontFamily: 'Poppins',
    fontSize: 12,
    lineHeight: 24,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
};
