const SET_CURRENT_USER = 'set_current_user';
const SET_SELECTED_ZCARD = 'set_seleted_zcard';

export {SET_CURRENT_USER, SET_SELECTED_ZCARD};

//Wallet Actions
export const SET_WALLET = 'SET_WALLET';

//Account Actions
export const SET_ACCOUNTS_DATA = 'SET_ACCOUNTS_DATA';
export const SET_INITIAL_ACCOUNT_DATA = 'SET_INITIAL_ACCOUNT_DATA';
export const SET_CURRENT_ACCOUNT_INDEX = 'SET_CURRENT_ACCOUNT_INDEX';

//Network Actions
export const SET_NETWORKS_DATA = 'SET_NETWORKS_DATA';
export const SET_CURRENT_NETWORK = 'SET_CURRENT_NETWORK';
export const SET_NETWORK_GAS_PRICE = 'SET_NETWORK_GAS_PRICE';

//balance actions
export const SET_BALANCE_UPDATED_INFO = 'SET_BALANCE_UPDATED_INFO';
export const SET_TOKEN_BALANCE_UPDATED_INFO = 'SET_TOKEN_BALANCE_UPDATED_INFO';

//tokens actions
export const SET_TOKENS_DATA = 'SET_TOKENS_DATA';
export const SET_SELECTED_TOKEN = 'SET_SELECTED_TOKEN';

//quote actions

//engine actions
export const SET_FEE_DATA = 'SET_FEE_DATA';
export const SET_GETTING_FEE_DATA_TIMER_ID = 'SET_GETTING_FEE_DATA_TIMER_ID';

//settings actions
export const SET_SETTINGS_DATA = 'SET_SETTINGS_DATA';
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';
export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
export const SET_SEARCH_ENGINE = 'SET_SEARCH_ENGINE';
export const SET_PRIVACY_CURRENCY = 'SET_PRIVACY_CURRENCY';
export const SET_AUTOLOCK_TIME = 'SET_AUTOLOCK_TIME';
